[database]
host = "db"
user = "postgres"
password = "postgres"
database = "IOC"

[api_keys]
virustotal = "db8072b6104d7793f3e380396b074dceb41b1c9f4809aecb3db48fe7dcd8e99f"
alienvault = "a793f7c4f4fa6a80e7c1e5ce878da1fd89972dec2301ea262972b5f67c25c236"
whoisxmlapi = "at_l6pq5CEHpIcdzlgddz6GDlpyySKx1"
abuseipdb = "45a8dc5f8873aa579efb2b4209f36eded777813270b627e1c07a4430c0dab2172cf30c7a1a3099cd"
blacklist_checker = "key_Nznpl6kxInHpBSLqCwTQvYZsg"
apininjas = "68IGOXcK4vaLLGoJQZjiog==GWaCdf7pT1EppJdN"
urlscan_io = "3aedcd7a-6efe-4fac-9c87-635cb4ba0c6a"
ipqualityscore = "01luL3gRILrQWqTfQBjIffJIbbkqLGw8"
greynoise = "cGz8nhmniWGNHExhhMokuGmByMnKWhfBkhglyeKdzlDzFk8rl3EOXr26pLvviqlP"
