[database]
host = "db"
user = ""
password = ""
database = ""

[api_keys]
virustotal = ""
alienvault = ""
whoisxmlapi = ""
abuseipdb = ""
blacklist_checker = ""
apininjas = ""
urlscan_io = ""
ipqualityscore = ""
greynoise = ""
